### ISSUE TITLE
import old mysql data ,get a problem

### ISSUE THREAD

**Issue by Goodahome** [MGeurts/genealogy#29] opened 2024-11-09 14:12 UTC
![image](https://github.com/user-attachments/assets/141eff5c-d07d-40fb-a0f5-87ba40ef503b)

**Comment by MGeurts** [comment] 2024-11-09 15:02
As always, please describe what you are trying to do in reproducible steps. Thank you.

**Comment by Goodahome** [comment] 2024-11-10 06:48
sorry, when i add person or edit person, click save button ,will get this problem ,i don`t know what different with database,i have watched it
![image](https://github.com/user-attachments/assets/da241f04-b31f-4f48-8f24-658a6e46f83b)

**Comment by MGeurts** [comment] 2024-11-10 08:32
Yes. that part was clear to me.
But what did you do with your database?
What do you mean with "**import old mysql data**"?
You can only import directly into the database when you know exactly what you are doing.
Otherwise, data wil not be consistent anymore.

**Comment by MGeurts** [comment] 2024-11-14 21:10
What's the status?
Can I close this issue?

**Comment by MGeurts** [comment] 2024-11-26 12:59
Closed due to no activity.

**Closed by MGeurts** 2024-11-26 12:59 UTC
